### ISSUE TITLE
Horizontal Scrollbar only at bottom of table, not bottom of note view

### ISSUE THREAD

**Issue by Snowflake6** [arturolinares/sn-rme#11]
When a table is generated that is wider than the note view, there is no horizontal scrollbar on the note view so you can scroll left and right within the table.  There *is*, however, a vertical scrollbar that lets you scroll vertically.

The note does appear to have a horizontal scrollbar, but it's at the bottom of the table, which means for large tables you have to scroll a long way down to find the scrollbar, scroll over, and then scroll all the way back up to where you were (which is now harder to find again because you've lost your row reference).

**Comment by arturolinares** [comment]
This is the expected behavior. You can scroll horizontally if your mouse supports it, or with a trackpad if you are in a laptop.

**Comment by Snowflake6** [comment]
But this is not expected behaviour for a user.  When using a UI that extends beyond the visible window, the scroll-bars appear to help you scroll around.  The vertical scroll-bar shows up.  The horizontal doesn't.  You don't have to scroll the table all the way to the right to find the up-down scrollbar, but you do have to scroll all the way to the bottom to find the horizontal scrollbar.

So the UI is inconsistent.

**Comment by arturolinares** [comment]
I haven't seen this behavior on any other application, but looks interesting. However, I think there are no plans to implement this in the original editor.

I'll close this for now, but if the feature is implemented upstream please feel free to reopen to integrate it.
