### ISSUE TITLE
[Feature Request] Support New Lines in Table Cell

### ISSUE THREAD

**Issue by kehphin** [arturolinares/sn-rme#12]
First off, this is an amazing editor and I'm using it every day now!

I have one small request - Currently when you insert a table, you cannot go to a new line in a cell, it will just add a new row to the table if you press ENTER. I would love multi line support in a cell, especially adding lists! 

Thanks much and keep up the good work :)

**Comment by nhalase** [comment]
You can press shift-enter to achieve this.

**Comment by arturolinares** [comment]
Yes, this was added in the latest version of the editor. To add a new line in a cell, use `shift+Enter`.
