### ISSUE TITLE
Start a new line in the same list item when pressing Ctrl+Enter

### ISSUE THREAD

**Issue by hirusi** [arturolinares/sn-rme#14]
Currently, if I have to start a new line within the same list item, I have to press enter, then backspace.

Ideally, this should be handled with a simple `Ctrl+Enter` keyboard shortcut.

**Comment by arturolinares** [comment]
@hirusi this is the expected behavior. You might want to suggest that hotkey on the editor issue tracker: https://github.com/outline/rich-markdown-editor/issues

**Comment by hlascelles** [comment]
Raised! https://github.com/outline/rich-markdown-editor/discussions/361

**Comment by hlascelles** [comment]
Works great now for me with SHIFT+ENTER. :+1:
