### ISSUE TITLE
Dictionary with limited vocabulary

### ISSUE THREAD

**Issue by DEV-D2** [arturolinares/sn-rme#15]
Are there any plans to support other dictionaries or a custom dictionary for the spell checker? A lot of words in my notes (mostly medical words e.g. atelectasis) are frequently underlined and it's hard to tell what's spelled correctly and what's not.

**Comment by arturolinares** [comment]
The dictionaries are part of the application (Standard Notes), not the editor. You can configure them in the menu Edit -> Spellchecker Languages.

![imagen](https://user-images.githubusercontent.com/203078/93045733-97d49f80-f61d-11ea-9ffe-9cf7ba40b647.png)

**Comment by arturolinares** [comment]
Closing this, the spell checker depends on the application, not the editor.
