### ISSUE TITLE
Excessive padding on top of first line

### ISSUE THREAD

**Issue by approveeldest** [arturolinares/sn-rme#21]
As you can see from the screenshot below, there's a big padding on top of the first line in the note editor:

![sn-rme-padding](https://user-images.githubusercontent.com/76448032/102807734-7b37c880-43bf-11eb-84b3-0cc23136b330.png)

The issue is reproducible also with the default Standard Notes theme, both on web (Firefox) and desktop (Linux). I am using the latest versions of Standard Notes (3.5.11) and Rich Markdown Editor (0.12.1).

**Comment by hlascelles** [comment]
I've had a go at this, and the fix is not perfect (codewise) but seems to do the job: https://github.com/arturolinares/sn-rme/pull/23

If someone has better css skills, do chime in.
