### ISSUE TITLE
Unable to toggle todo checkboxes

### ISSUE THREAD

**Issue by andersmmg** [arturolinares/sn-rme#22]
They used to work, but now clicking them does nothing. Nothing out of the ordinary otherwise, even in console.

**Comment by arturolinares** [comment]
Do you have more information on this? Does it happen on mobile?

I can toggle checkboxes by clicking on them on Desktop (Linux).

**Comment by andersmmg** [comment]
I haven't seen it recently the few times I've used it, so it might be fine now
