### ISSUE TITLE
New release with bullet point linebreak key

### ISSUE THREAD

**Issue by hlascelles** [arturolinares/sn-rme#24]
Rich markdown editor has [a change](https://github.com/outline/rich-markdown-editor/commit/96e50285087dffcdd4d99f9a7941174fc7ccdc73) that allows line breaks in bullet lists using SHIFT-ENTER. I believe it is now in v11.3.1.

Can we get a new release of this SN plugin with that in please? More generally, how would you like to be asked/notified of updates? Thanks.

**Comment by arturolinares** [comment]
This should be fixed now :)
