### ISSUE TITLE
Deletes line of text when style applied

### ISSUE THREAD

**Issue by shanemc92** [arturolinares/sn-rme#5]
If there's plain text in the note and you insert a '/' in front of it to access the full style menu, it deletes the line after a style is chosen rather than applying it to the line.
![2020-08-23_18-22-56](https://user-images.githubusercontent.com/47665742/90984572-b2ab7b00-e56d-11ea-9dca-7563202804b4.gif)

**Comment by bipox** [comment]
Is it by design?
I keep deleting lines by mistake

**Comment by arturolinares** [comment]
Yes. I just checked with their editor in getoutline.com and it behaves the same.

As a workaround, instead of using the menu to apply the style you can use a markdown shortcut. For example, if you want to turn the line to a header, at the start of the line add a # and then hit space.

**Comment by bipox** [comment]
> if you want to turn the line to a header, at the start of the line add a # and then hit space

Yeah, changing a line retroactively in markdown is what I'm used to, I think that's why I'm making this mistake. 

Thanks for checking!
