### ISSUE TITLE
Dividers are not displayed when a note is opened

### ISSUE THREAD

**Issue by rubengersons** [arturolinares/sn-rme#6]
When I add a divider to a note (---) a nice divider is added. However, if I then switch to another note and then back, the divider is not being displayed.
If I switch to plain editor I can see the 3 dashes (---) are still there, so probably just a rendering issue.

PS: awesome editor!

**Comment by shompoe** [comment]
I am having the same problem. Dividers seem to be automatically removed when the note is loaded.

**Comment by Wintercypher** [comment]
So I believe I have figured out a workaround for this issue. It comes down to proper spacing of the horizontal line. I was getting frustrated that I would put the lines in place and then watch the UI confirm that it was saved. I would click on another note and then come back to original note to see all of my 'dividers' were gone. I decided to edit the note in another markdown editor and then change to editor back to the RME editor. This is when I noticed a difference in the markdown method. 

Note the additional space below the H2 before the divider is placed. If this space is missing, the divider disappears when I toggle the note. 
```
## Topics

---
1. 

```

Heres the problem though, the line stays the first time you change the editor and will stay in place UNTIL you edit the note again. Then the divider disappears.

**Comment by BrunoBernardino** [comment]
This is quite annoying, and I'd love to help fix this. It doesn't look like the problem's with https://github.com/outline/rich-markdown-editor though. Any ideas/suggestions for me to help debug and fix this? Apart from this, I'm really enjoying this editor.

**Comment by BrunoBernardino** [comment]
My PR above has a published link for a version of the editor that has this issue fixed, if you're interested.

**Comment by arturolinares** [comment]
Thank you @BrunoBernardino! I'll merge today, and probably reorganize a little the code because it's impossible to review PRs as it is now.
