### ISSUE TITLE
Excessive permissions

### ISSUE THREAD

**Issue by mobitar** [arturolinares/sn-rme#7]
Cool editor! Just a heads up that you shouldn't be needing all these permissions: https://github.com/arturolinares/sn-rme/blob/master/src/lib/BridgeManager.js#L50

Simply streaming the context item (the current note) should be sufficient. You shouldn't need to access the user's other editors/components, themes, and server extensions.

**Comment by arturolinares** [comment]
Thank you! I'll send a fix soon.
