### ISSUE TITLE
Notice Bars Spacing

### ISSUE THREAD

**Issue by shanemc92** [arturolinares/sn-rme#8]
The notice bars automatically add spaces when the note is closed and opened again. If multiple bars are placed next to each other, backspacing the line in between sticks them together and pressing the Del key to remove the space turns the bar below to plaintext. 

![2020-08-26_10-20-52](https://user-images.githubusercontent.com/47665742/91286553-79018c80-e786-11ea-8582-7a0fb27b7db5.gif)

**Comment by arturolinares** [comment]
0.18 should fix this one :)
